### ISSUE TITLE
Should not throw an error if no window is focused

### ISSUE THREAD

**Issue by real-or-random** [flexagoon/focused-window-dbus#1]
The extensions spams the log when no windows is focused:

```
Feb 21 09:31:31 gnome-shell[18806]: JS ERROR: Exception in method call: Get: Error: No window in focus
                                    Get@/home/tim/.local/share/gnome-shell/extensions/focused-window-dbus@flexagoon.com/extension.js:56:19
                                    _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:324:38
                                    _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:401:34
```

**Comment by flexagoon** [comment]
I agree, it shouldn't throw an error. However, aw-watcher-gnome currently [depends](https://github.com/flexagoon/aw-watcher-gnome/blob/886e48f501713d8e80064f1d0fa24fd9db16d9ce/aw_watcher_gnome/watcher.py#L110) on this behavior to check if the screen is off

So this change will also require a slight rework in aw-watcher-gnome. I'll probably do this together with implementing screen lock detection as you suggested in https://github.com/flexagoon/aw-watcher-gnome/issues/3

**Comment by real-or-random** [comment]
Thanks for the quick reply, sounds awesome.

And thanks for starting this project, it's already very helpful. And yes, this is very new and has still a few rough edges, of course. I may open additional issues if I encounter more, if you don't mind.

**Comment by flexagoon** [comment]
@real-or-random 

> I may open additional issues if I encounter more, if you don't mind.

Of course! Unfortunately, I don't really have the time to work on this right now, but I will eventually fix the issues you encounter. Feel free to report bugs or feature suggestions, I'm honestly really happy that someone found my project useful!
