### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by RedBearAK** [flexagoon/focused-window-dbus#3]
@flexagoon 

Hi, I just want to let you know that for some time now I have integrated your extension as one of the options that allows my project to support app-specific (and window-specific) keyboard shortcut remaps on Wayland+GNOME, by providing a way to grab the app class and window title. 

I have a couple of other compatible extension options: 

- Window Calls Extended
- Xremap

All three extensions can be installed and enabled, and my project will use the first one it finds responding to queries, and will transparently jump to another one if the active extension is disabled. 

Yours is the newest extension, from what I can tell, and I only found it by accident while searching extensions for "focus", which is part of the description of the Xremap extension. 

Having three different extensions being compatible with my project means my users will be more likely to have an extension available for any new GNOME version to keep my project working. But the other extensions also support older versions of GNOME, with Xremap supporting GNOME back to 3.38, which turned out to be needed for Zorin OS. 

As of today the Extension Manager app scans your extension as not supporting GNOME 45. I've heard that GNOME 45 will be pretty disruptive to extensions that don't get updated. It would be very much appreciated if your extension could be one of those that is compatible with GNOME 45 before the beta period is over. I use Fedora and they generally move onto the latest GNOME release with each of their 6-month releases. 

Thanks for the extension. 👍🏽  

My project: 

https://github.com/RedBearAK/toshy

**Comment by flexagoon** [comment]
Hi! The window information API that this extension is using is unlikely to change between GNOME releases, so supporting GNOME 45 is probably as simple as adding `45` to [the list of supported versions](https://github.com/flexagoon/focused-window-dbus/blob/3c091d9ef5ca763e7643d4b0c7479ef36c6c52ac/metadata.json#L7).

I can go ahead and add it right now, but it'd still be nice to test it first in case the API did actually change somehow. Do you have access to GNOME 45 to help me test if the extension works on it?

**Comment by RedBearAK** [comment]
> Do you have access to GNOME 45 to help me test if the extension works on it?

I do have Fedora 39 beta in a GNOME Boxes VM, where they are already on GNOME 45. I used the "Everything boot" last-known-good ISO build from here, right at the top in the Fedora 39 column: 

https://openqa.fedoraproject.org/nightlies.html  

I saw someone else posting in the GNOME subreddit about wanting to test their extension on GNOME 45, and the F39 beta ISO was one of the main things mentioned where they already have G45 integrated. 

One can hope that it will be as easy as changing the version number, but the articles have been claiming that all current extensions are using a couple of instructions that will need to be replaced because the module type is changing. Or something. 

Thanks for the response. I can test any time. I already have my project set up in the F39 beta VM and working in X11/Xorg so as soon as I switch to Wayland there will be no extension active because they are all claiming to be incompatible right now. Should I try the trick where you just go edit the extension file and make it think it's compatible with "45"?

**Comment by RedBearAK** [comment]
@flexagoon 

I tried the trick of just adding the "45" to the version list and rebooted to make sure it would take effect. 

As I kind of expected, there is now an error shown in Extension Manager: 

```sh
import declarations may only appear at top level of a module
```

I think this is what all extension devs are having to deal with when moving to GNOME 45. There's a migration guide most of the articles about this are linking to. 

https://gjs.guide/extensions/upgrading/gnome-shell-45.html#extensionutils  

This is not an area I'm familiar with. 

https://debugpointnews.com/gnome-extensions-break/  

https://news.itsfoss.com/gnome-45-extensions/  

So, as of now my project is not usable in a Wayland session with the GNOME 45 beta, because none of the compatible extensions have been updated yet. 

Seems like quite a high percentage of the extensions I have installed are not yet scanning as compatible yet, so you're not alone.

**Comment by flexagoon** [comment]
@RedBearAK thanks! I'm not that familiar with JavaScript or GJS either, but the fix doesn't seem too hard. I'll try fixing it today.

**Comment by RedBearAK** [comment]
@flexagoon 

I can't be sure about the `log()` line, but otherwise I seem to have managed to get it working on the Fedora 39 beta VM. I left the original lines in as comments. There may be some things you'd want to do differently. I know there's a way to reload extensions after you change them, but I forget how to do it, so I was just logging out or rebooting every time I thought I might have made all the necessary changes. I was wrong several times. 💀 

This in particular was just pulled from the porting guide without fully understanding why it's written that way, it's from one of their examples and probably needs modification:  

```js
// const ExtensionUtils = imports.misc.extensionUtils;
import {Extension, gettext as _} from 'resource:///org/gnome/shell/extensions/extension.js';
```

What I ended up with that works: 

```js
'use strict';

// const ExtensionUtils = imports.misc.extensionUtils;
import {Extension, gettext as _} from 'resource:///org/gnome/shell/extensions/extension.js';
// const Me = ExtensionUtils.getCurrentExtension();
import * as MyModule from './extension.js';
// const Gio = imports.gi.Gio;
import Gio from 'gi://Gio';

const DBUS_SCHEMA = `
<node>
    <interface name="org.gnome.shell.extensions.FocusedWindow">
        <method name="Get">
            <arg type="s" direction="out" name="window" />
        </method>
    </interface>
</node>`;

// class Extension {
export default class MyExtension {
    Get() {
        let window_list = global.get_window_actors();
        let focusedWindow = window_list.find(window => window.meta_window.has_focus());

        // Stolen from the "Window Calls" extension
        // https://github.com/ickyicky/window-calls/blob/b5ac7abe7e7acfcced75c5139824bd434d7c8f89/extension.js#L129
        let workspaceManager = global.workspace_manager;
        let currentmonitor = global.display.get_current_monitor();
        if (focusedWindow) {
            return JSON.stringify({
                title: focusedWindow.meta_window.get_title(),
                wm_class: focusedWindow.meta_window.get_wm_class(),
                wm_class_instance: focusedWindow.meta_window.get_wm_class_instance(),
                pid: focusedWindow.meta_window.get_pid(),
                id: focusedWindow.meta_window.get_id(),
                width: focusedWindow.get_width(),
                height: focusedWindow.get_height(),
                x: focusedWindow.get_x(),
                y: focusedWindow.get_y(),
                focus: focusedWindow.meta_window.has_focus(),
                in_current_workspace: focusedWindow.meta_window.located_on_workspace(workspaceManager.get_active_workspace()),
                moveable: focusedWindow.meta_window.allows_move(),
                resizeable: focusedWindow.meta_window.allows_resize(),
                canclose: focusedWindow.meta_window.can_close(),
                canmaximize: focusedWindow.meta_window.can_maximize(),
                maximized: focusedWindow.meta_window.get_maximized(),
                canminimize: focusedWindow.meta_window.can_minimize(),
                display: focusedWindow.meta_window.get_display(),
                frame_type: focusedWindow.meta_window.get_frame_type(),
                window_type: focusedWindow.meta_window.get_window_type(),
                layer: focusedWindow.meta_window.get_layer(),
                monitor: focusedWindow.meta_window.get_monitor(),
                role: focusedWindow.meta_window.get_role(),
                area: focusedWindow.meta_window.get_work_area_current_monitor(),
                area_all: focusedWindow.meta_window.get_work_area_all_monitors(),
                area_cust: focusedWindow.meta_window.get_work_area_for_monitor(currentmonitor)
            });
        } else {
            throw new Error('No window in focus');
        }
    }

    enable() {
        this._dbus = Gio.DBusExportedObject.wrapJSObject(DBUS_SCHEMA, this);
        this._dbus.export(Gio.DBus.session, '/org/gnome/shell/extensions/FocusedWindow');
    }

    disable() {
        this._dbus.flush();
        this._dbus.unexport();
        delete this._dbus;
    }
}

function init() {
//    log(`initializing ${Me.metadata.name}`);
    log(`initializing ${MyModule.metadata.name}`);
//    return new Extension();
    return new MyExtension();
}
```

**Comment by flexagoon** [comment]
@RedBearAK thanks! Can you create a pull request so that I could merge your changes? Also, does the changed code continue to work on GNOME 44?

**Comment by RedBearAK** [comment]
@flexagoon 

I think because of the fundamental nature of the change that separate versions of all extensions have to be uploaded for pre-45 GNOME and GNOME 45 or later. But I didn’t get into how that is done.

**Comment by RedBearAK** [comment]
@flexagoon 

Every source I've seen (including the porting guide) says that the only way to do the transition is to create a separate upload to the extensions site. 

Seems like a good idea to create a new branch here (like `pre_GNOME_45`) to pin the state of the extension that works with GNOME 44 and earlier, in case you need to fix something in that branch and make a new version to upload after the main branch becomes GNOME 45+ only. 

Not sure how else to manage the transition, besides keeping archival copies of the older version of the extension. I would not want to lose access to the earlier versions. A number of distros are very slow to move to new GNOME releases. I expect some distros like RHEL/AlmaLinux or openSUSE Leap/SLES to take anywhere from 2 to 4 years to finally get on GNOME 45.

**Comment by RedBearAK** [comment]
@flexagoon 

Submitted tested changes as PR #4. Only apparent issue is nothing coming out in the journal for the log line.

**Comment by flexagoon** [comment]
Thanks! I submitted the version with your fixes for review

https://extensions.gnome.org/review/45373

I'll close this issue once it gets approved.

**Comment by RedBearAK** [comment]
@flexagoon 

I appreciate your time. Your extension may end up being the first of the three that make my project usable in GNOME to be compatible with GNOME 45. Only a little over half the extensions I use are now scanning as supported. An improvement from a week ago, but things are moving slowly and some distros are already jumping onto the GNOME 45 release. (Arch, Tumbleweed, some distro betas like Fedora 39.) So this will be nice to have available. 

> I'll close this issue once it gets approved.

That was my plan as well. Extension Manager should let me know, though I suppose you'll get an email or something when it gets accepted.

**Comment by flexagoon** [comment]
@RedBearAK 

> Only a little over half the extensions I use are now scanning as supported

I just checked and there are only two extensions I'm using which don't have GNOME 45 support yet. One of them ([Run Or Raise](https://github.com/CZ-NIC/run-or-raise/)) is working on it. The other though, [Rounded Window Corners](https://github.com/yilozt/rounded-window-corners) doesn't have any recent commits at all, and I really hope it'll get updated, because it's such a significant UI improvement imo

> some distros are already jumping onto the GNOME 45 release. (Arch, Tumbleweed, some distro betas like Fedora 39.)

I don't know about other distros, but the planned release date for Fedora 39 is in a month, so I guess there still is some time

> That was my plan as well. Extension Manager should let me know, though I suppose you'll get an email or something when it gets accepted.

Yes, I will get an email

**Comment by flexagoon** [comment]
@RedBearAK the new version was rejected with the following comment:

> 1. Please remove line 76-80. Not needed anymore.
> 
> 2. Please use non generic names for the class you are exporting for back tracing (line 13).

**Comment by flexagoon** [comment]
Alright, I fixed the issue in https://github.com/flexagoon/focused-window-dbus/commit/89ab6fc80ff3ca3eccd666086bc785e0735d028e, I'll submit the extension again now

**Comment by RedBearAK** [comment]
@flexagoon 

> planned release date for Fedora 39 is in a month

Yes, but some have been upgrading to the beta for a while now even before the beta was officially announced, and raving about it on the Fedora subreddit daily now that the beta is out. With GNOME 45 being a primary motivator for jumping into it so early.

**Comment by RedBearAK** [comment]
> Alright, I fixed the issue in [89ab6fc](https://github.com/flexagoon/focused-window-dbus/commit/89ab6fc80ff3ca3eccd666086bc785e0735d028e), I'll submit the extension again now

Wondered about that class name, but I didn’t want to go too crazy changing things. 

Interesting that the init is not necessary anymore.

**Comment by flexagoon** [comment]
Done!

https://extensions.gnome.org/extension/5592/focused-window-d-bus/

Thank you @RedBearAK for your contribution! 🤍

**Comment by RedBearAK** [comment]
@flexagoon 

Fantastic. Thanks for being responsive to updating it.
